// functions/api/bizbuilder/pdf.js
// GET /api/bizbuilder/pdf?token=<access_token>
// Token-gated PDF of the buyer's complete BizBuilder deliverable:
// the one-page business plan, the landing-page copy, and the 5-email
// welcome sequence. Built server-side with the vendored pdf-lib bundle
// (standard Helvetica — no font files). Only serves orders with status='ready'.

import { PDFDocument, StandardFonts, rgb } from "./_lib/pdf-lib.bundle.js";

const PW = 612; // Letter
const PH = 792;
const MARGIN = 54;
const CONTENT_W = PW - MARGIN * 2;

function wrapText(font, text, size, maxWidth) {
  const words = String(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";
  for (const w of words) {
    const trial = line ? line + " " + w : w;
    if (font.widthOfTextAtSize(trial, size) <= maxWidth) {
      line = trial;
    } else {
      if (line) lines.push(line);
      // a single word wider than the column: hard-split it
      let rest = w;
      while (font.widthOfTextAtSize(rest, size) > maxWidth && rest.length > 1) {
        let cut = rest.length - 1;
        while (cut > 1 && font.widthOfTextAtSize(rest.slice(0, cut), size) > maxWidth) cut--;
        lines.push(rest.slice(0, cut));
        rest = rest.slice(cut);
      }
      line = rest;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function onRequestGet({ request, env }) {
  const token = new URL(request.url).searchParams.get("token") || "";
  if (token.length < 16) {
    return Response.json({ ok: false, error: "invalid_token" }, { status: 403 });
  }
  const order = await env.LEADS_DB.prepare(
    "SELECT * FROM bizbuilder_orders WHERE access_token = ?"
  ).bind(token).first();
  if (!order) {
    return Response.json({ ok: false, error: "unknown_order" }, { status: 404 });
  }
  if (order.status !== "ready" || !order.output_json) {
    return Response.json(
      { ok: false, error: "not_ready", status: order.status },
      { status: 409 }
    );
  }
  let manifest;
  try {
    manifest = JSON.parse(order.output_json);
  } catch {
    return Response.json({ ok: false, error: "manifest_corrupt" }, { status: 500 });
  }
  const raw = (manifest.files || []).find((f) => f.name === "plan.json");
  if (!raw) {
    return Response.json({ ok: false, error: "plan_missing" }, { status: 500 });
  }
  let data;
  try {
    data = JSON.parse(raw.content);
  } catch {
    return Response.json({ ok: false, error: "plan_corrupt" }, { status: 500 });
  }
  const plan = data.plan || {};

  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg = await doc.embedFont(StandardFonts.Helvetica);

  const dark = rgb(0.06, 0.09, 0.16);
  const green = rgb(0.13, 0.58, 0.35);
  const gray = rgb(0.45, 0.48, 0.55);

  let page = doc.addPage([PW, PH]);
  let y = PH - MARGIN;

  function newPage() {
    page = doc.addPage([PW, PH]);
    y = PH - MARGIN;
  }
  function ensure(space) {
    if (y - space < MARGIN + 24) newPage();
  }
  function text(str, { size = 11, font = reg, color = dark, gap = 5, indent = 0 } = {}) {
    const lines = wrapText(font, str, size, CONTENT_W - indent);
    ensure(lines.length * (size + gap));
    for (const ln of lines) {
      y -= size + gap;
      page.drawText(ln, { x: MARGIN + indent, y, size, font, color });
    }
  }
  function heading(str) {
    ensure(44);
    y -= 30;
    const lines = wrapText(bold, str, 15, CONTENT_W);
    for (const ln of lines) {
      page.drawText(ln, { x: MARGIN, y, size: 15, font: bold, color: green });
      y -= 21;
    }
    y -= 2;
  }

  // Title block
  const title = String(plan.title || manifest.title || "Business Plan").slice(0, 100);
  const tw = wrapText(bold, title, 24, CONTENT_W);
  ensure(tw.length * 32 + 20);
  for (const ln of tw) {
    y -= 32;
    page.drawText(ln, { x: MARGIN, y, size: 24, font: bold, color: dark });
  }
  y -= 8;
  text("One-page business plan — generated by BizBuilder", { size: 10, color: gray, gap: 4 });
  y -= 6;

  const sections = [
    ["The Concept", plan.concept],
    ["Target Customer", plan.target_customer],
    ["The Offer", plan.the_offer],
    ["Pricing & Unit Economics", plan.pricing_and_unit_economics],
    ["Go-to-Market: First 30 Days", plan.go_to_market_30_days],
    ["Startup Costs", plan.startup_costs],
    ["Risks & Honest Caveats", plan.risks_and_caveats],
  ];
  for (const [label, body] of sections) {
    if (!body) continue;
    heading(label);
    for (const chunk of String(body).split(/\n{2,}|\n- /)) {
      const t = chunk.trim().replace(/^[•\-]\s*/, "");
      if (t) text(t, { indent: 0 });
    }
  }
  heading("90-Day Milestones");
  for (const m of plan.milestones_90_days || []) {
    text("• " + m, { indent: 6 });
  }

  // ── Landing-page copy ──
  const landing = data.landing || {};
  function sectionTitle(str) {
    newPage();
    const lines = wrapText(bold, str, 20, CONTENT_W);
    for (const ln of lines) {
      y -= 28;
      page.drawText(ln, { x: MARGIN, y, size: 20, font: bold, color: dark });
    }
    y -= 10;
  }
  // Strip light markdown so the PDF reads clean.
  function cleanMd(s) {
    return String(s || "")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/__([^_]+)__/g, "$1")
      .replace(/^#{1,6}\s+/gm, "")
      .replace(/(^|\s)_([^_]+)_(\s|$)/g, "$1$2$3");
  }
  function para(s, opts) {
    for (const chunk of cleanMd(s).split(/\n{2,}|\n/)) {
      const t = chunk.trim();
      if (t) text(t, opts);
    }
  }
  if (landing.hero_headline || (landing.benefits || []).length) {
    sectionTitle("Landing-Page Copy");
    if (landing.hero_headline) {
      text(cleanMd(landing.hero_headline), { size: 16, font: bold, color: dark, gap: 6 });
    }
    if (landing.hero_subhead) para(landing.hero_subhead, { size: 12 });
    if (landing.hero_cta) text("Call to action: " + cleanMd(landing.hero_cta), { size: 11, color: gray });
    y -= 6;
    if ((landing.benefits || []).length) {
      heading("Benefits");
      for (const b of landing.benefits) {
        if (b.title) text(cleanMd(b.title), { size: 12, font: bold, gap: 4 });
        if (b.body) para(b.body);
        y -= 4;
      }
    }
    if ((landing.how_it_works || []).length) {
      heading("How It Works");
      landing.how_it_works.forEach((s, i) => para(`${i + 1}. ${cleanMd(s)}`));
    }
    if ((landing.faq || []).length) {
      heading("FAQ");
      for (const f of landing.faq) {
        if (f.q) text("Q: " + cleanMd(f.q), { size: 11, font: bold, gap: 4 });
        if (f.a) para("A: " + cleanMd(f.a));
        y -= 4;
      }
    }
    if (landing.final_cta) {
      y -= 4;
      para(cleanMd(landing.final_cta), { size: 12, font: bold, color: green });
    }
  }

  // ── 5-email welcome sequence ──
  const emailsObj = data.emails || {};
  const emailList = emailsObj.emails || [];
  if (emailList.length) {
    sectionTitle("5-Email Welcome Sequence");
    for (const e of emailList) {
      heading(`Day ${e.day || "?"} — ${cleanMd(e.subject || "Untitled")}`);
      if (e.preview) text("Preview: " + cleanMd(e.preview), { size: 10, color: gray, gap: 4 });
      if (e.body) para(e.body);
      y -= 8;
    }
  }

  // Footer on every page
  const pages = doc.getPages();
  for (const p of pages) {
    const foot = "BizBuilder · bizbuilder.mehyar.us · A starting point, not financial advice.";
    const fw = reg.widthOfTextAtSize(foot, 8);
    p.drawText(foot, { x: (PW - fw) / 2, y: 28, size: 8, font: reg, color: gray });
  }

  const bytes = await doc.save();
  const filename = title.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "business-plan";
  return new Response(bytes, {
    status: 200,
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `attachment; filename="${filename}-complete.pdf"`,
      "cache-control": "private, no-store",
    },
  });
}
